### ISSUE TITLE
Cannot read property 'toString' of undefined when using raw queries and regex'ing out values - Query works 

### ISSUE THREAD

**Issue by SamuelmAsh** [neuralfraud/grafana-prtg#105]
Hi @neuralfraud  i was attempting to get the readout of current alarm status with getstatus.htm  I have the query working ok but when trying to regex the alarms value for a singestat panel i get the Cannot read property 'toString' of undefined error 

`Message:
Cannot read property 'toString' of undefined
Stack trace:
TypeError: Cannot read property 'toString' of undefined
    at e.isMsResolutionNeeded (http://172.20.7.135:3000/public/build/app.5372b9bbcb8c6d1c027e.js:1:17644)
    at new e (http://172.20.7.135:3000/public/build/app.5372b9bbcb8c6d1c027e.js:1:14477)
    at e.seriesHandler (http://172.20.7.135:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:310156)
    at Array.map (<anonymous>)
    at e.onDataReceived (http://172.20.7.135:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:310032)
    at o.emit (http://172.20.7.135:3000/public/build/vendor.0cea50118711e7e6c839.js:44:25321)
    at e.emit (http://172.20.7.135:3000/public/build/app.5372b9bbcb8c6d1c027e.js:1:13178)
    at e.handleQueryResult (http://172.20.7.135:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:18161)
    at u (http://172.20.7.135:3000/public/build/vendor.0cea50118711e7e6c839.js:87:69119)
    at http://172.20.7.135:3000/public/build/vendor.0cea50118711e7e6c839.js:87:69565`

Any advice ?

**Comment by Yakelixir** [comment]
Can you provide some more details on the request and what your query looks like? I can try to reproduce this.
