### ISSUE TITLE
PRTG - JSON error :(

### ISSUE THREAD

**Issue by SlodeSoft** [neuralfraud/grafana-prtg#21]
Hi all,

i get this error message when i configure any query : 

Grafana version: 2.5.0, commit: v2.5.0+1-g287d8ca
PRTG : PRTG Network Monitor 16.3.25.6072 x64 (Licence FREE 100) (Just for test)

Message:
            Unexpected token 
 in JSON at position 347

Stack trace:
            SyntaxError: Unexpected token 
 in JSON at position 347
    at Object.parse (native)
    at new xmlXform (http://[IP]:3000/public/app/plugins/datasource/PRTG/xmlparser.js?bust=1473245533497:148:17)
    at http://[IP]:3000/public/app/plugins/datasource/PRTG/api_wrapper.js?bust=1473245533497:175:20
    at i (http://[IP]:3000/app/app.b4b243aa.js:13:3780)
    at http://[IP]:3000/app/app.b4b243aa.js:13:3952
    at n.$eval (http://[IP]:3000/app/app.b4b243aa.js:13:11572)
    at n.$digest (http://[IP]:3000/app/app.b4b243aa.js:13:10003)
    at n.$apply (http://[IP]:3000/app/app.b4b243aa.js:13:11839)
    at f (http://[IP]:3000/app/app.b4b243aa.js:12:18511)
    at r (http://[IP]:3000/app/app.b4b243aa.js:12:20308

**Comment by neuralfraud** [comment]
What commit/branch did you download? this happens when PRTG outputs empty XML, but the most recent "old" build should have a fix for that.

**Comment by SlodeSoft** [comment]
What commit/branch did you download?

The last !

Now it's good for me !
thanks for you answer !
