### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by jaxxstorm** [neuralfraud/grafana-prtg#5]
```
Message:
			Unexpected end of input
		
Stack trace:
			SyntaxError: Unexpected end of input
    at Object.parse (native)
    at new xmlXform (https://host.example.com/public/app/plugins/datasource/PRTG/xmlparser.js?bust=1450216354962:156:17)
    at https://host.example.com/public/app/plugins/datasource/PRTG/api_wrapper.js?bust=1450216354962:179:20
    at i (https://host.example.com/app/app.a44ece05.js:13:3780)
    at https://host.example.com/app/app.a44ece05.js:13:3952
    at n.$eval (https://host.example.com/app/app.a44ece05.js:13:11572)
    at n.$digest (https://host.example.comapp/app.a44ece05.js:13:10003)
    at n.$apply (https://host.example.com/app/app.a44ece05.js:13:11839)
    at f (https://host.example.com/app/app.a44ece05.js:12:18511)
    at r (https://host.example.com/app/app.a44ece05.js:12:20308)
```

Anything I can do to help you debug here?

**Comment by jaxxstorm** [comment]
Similar issue:

```
Message:
			Unexpected token <
		
Stack trace:
			SyntaxError: Unexpected token <
    at Object.parse (native)
    at W (https://host.example.com/app/app.a44ece05.js:10:10722)
    at tb (https://host.example.com/app/app.a44ece05.js:12:15673)
    at https://host.example.com/app/app.a44ece05.js:12:16142
    at f (https://host.example.com/app/app.a44ece05.js:10:6223)
    at xb (https://host.example.com/app/app.a44ece05.js:12:16124)
    at e (https://host.example.com/app/app.a44ece05.js:12:16777)
    at i (https://host.example.com/app/app.a44ece05.js:13:3780)
    at https://host.example.com/app/app.a44ece05.js:13:3952
    at n.$eval (https://host.example.com/app/app.a44ece05.js:13:11572)
```

**Comment by jaxxstorm** [comment]
API version:

```
PRTG API version: 15.1.13.1090
```

**Comment by neuralfraud** [comment]
View the histdata.xml response. That happens when there isn't any data or
there is an issue. The xsl expects it to always be a data set and when the
api returns an error response you get the parse error. I might be able to
do away with that though since I changed the way values are read.

**Comment by jaxxstorm** [comment]
I checked the histdata, it's definitely returning values. I get a nice graph for CPU, assuming I set the timeframe to something like the last day, but nothing for SNMP based sensors. I can attach my hist data if you need some output

I also updated my API version to ensure that wasn't it.

**Comment by neuralfraud** [comment]
Can you provide a sample of the root node tag and maybe an item block? Unfortunately I have to rely on XSL at the moment.

**Comment by neuralfraud** [comment]
The parse error happens because the first XSL transformation fails, which is usually due to a node missing, which is usually caused by a particular sensor not having data for the given time range. For instance, Windows Updates Status checks less frequently, so if I select a server with the view set to "last hour", those will show the same error. For the displays that aren't rendering, please verify the sensor scan interval. I think there's a better way to handle that which won't generate such an ugly error message using Grafana's built-in notifications.

**Comment by neuralfraud** [comment]
I've resolved this issue. PRTG returns "Not enough data available." when there are no data points for a given time range. The text causes the XSL barfs, which in turn causes the JSON.parse() to barf. I added response check condition that returns a nice error message along with the parameters of the request which failed.
